let currentMode = 'bitwise';

// UI DOM Elements
let modeSelect, bitwiseOpSelect;
let bitwisePointsSlider, bitwiseColorSlider;
let treeAngleSlider, treeScaleSlider, treeDepthSlider, treeWindSlider;
let iterationsSlider, zoomSlider, crSlider, ciSlider, paletteSelect;

// Sizing
let canvasSize = 512;
let pixelScale = 1; // dynamically adjusted for speed (Mandelbrot/Julia)
let isInteracting = false;
let interactionTimer = 0;

// Tree parameters
let windAngle = 0;

p5.disableFriendlyErrors = true; // maximize performance

function setup() {
  const holder = document.getElementById('p5-canvas-holder');
  const canvas = createCanvas(canvasSize, canvasSize);
  canvas.parent('p5-canvas-holder');
  
  pixelDensity(1); // prevent Retina/4K displays from lagging
  
  // Bind UI Elements
  modeSelect = select('#modeSelect');
  bitwiseOpSelect = select('#bitwiseOp');
  bitwisePointsSlider = select('#bitwisePointsSlider');
  bitwiseColorSlider = select('#bitwiseColorSlider');
  treeAngleSlider = select('#treeAngleSlider');
  treeScaleSlider = select('#treeScaleSlider');
  treeDepthSlider = select('#treeDepthSlider');
  treeWindSlider = select('#treeWindSlider');
  iterationsSlider = select('#iterationsSlider');
  zoomSlider = select('#zoomSlider');
  crSlider = select('#crSlider');
  ciSlider = select('#ciSlider');
  paletteSelect = select('#colorPalette');
  
  // Handle Mode Switching
  modeSelect.changed(onModeChange);
  
  // Attach listeners to detect slider interaction for fast preview resolution
  const inputs = document.querySelectorAll('input[type="range"], select');
  inputs.forEach(input => {
    input.addEventListener('input', triggerFastMode);
    input.addEventListener('change', triggerFastMode);
  });
  
  resetCanvas();
}

function draw() {
  // Update interaction timers to fade back to full resolution
  if (isInteracting) {
    pixelScale = 3; // low res for high speed updates
    if (millis() - interactionTimer > 350) {
      isInteracting = false;
      pixelScale = 1; // render final clean frame
      background(10); // trigger redraw
    }
  }

  // Choose visual execution path
  if (currentMode === 'bitwise') {
    drawBitwise();
  } else if (currentMode === 'tree') {
    drawTree();
  } else if (currentMode === 'mandelbrot') {
    drawMandelbrot();
  } else if (currentMode === 'julia') {
    drawJulia();
  }
  
  // Draw HUD text logs
  updateHUD();
}

function onModeChange() {
  currentMode = modeSelect.value();
  
  // Toggle UI control block display
  const bitwiseCtrls = document.getElementById('bitwiseControls');
  const treeCtrls = document.getElementById('treeControls');
  const complexCtrls = document.getElementById('complexControls');
  const juliaConstants = document.getElementById('juliaConstantControls');
  
  const bitwiseInfo = document.getElementById('bitwiseInfo');
  const treeInfo = document.getElementById('treeInfo');
  const complexInfo = document.getElementById('complexInfo');
  const complexFormulaText = document.getElementById('complexFormulaText');
  
  // Hide all first
  bitwiseCtrls.classList.add('hidden');
  treeCtrls.classList.add('hidden');
  complexCtrls.classList.add('hidden');
  juliaConstants.classList.add('hidden');
  bitwiseInfo.classList.add('hidden');
  treeInfo.classList.add('hidden');
  complexInfo.classList.add('hidden');
  
  resetCanvas();
  
  // Show active set
  if (currentMode === 'bitwise') {
    bitwiseCtrls.classList.remove('hidden');
    bitwiseInfo.classList.remove('hidden');
  } else if (currentMode === 'tree') {
    treeCtrls.classList.remove('hidden');
    treeInfo.classList.remove('hidden');
  } else if (currentMode === 'mandelbrot') {
    complexCtrls.classList.remove('hidden');
    complexInfo.classList.remove('hidden');
    complexFormulaText.textContent = "A set mapped in the complex plane. Mandelbrot checks convergence for c starting at z₀=0. Grid coordinates represent variable complex parameters c.";
  } else if (currentMode === 'julia') {
    complexCtrls.classList.remove('hidden');
    juliaConstants.classList.remove('hidden');
    complexInfo.classList.remove('hidden');
    complexFormulaText.textContent = "Julia sets are generated by keeping c constant and varying z₀. Drag your mouse inside the canvas coordinates to dynamically morph the Julia shapes!";
  }
}

function triggerFastMode() {
  isInteracting = true;
  interactionTimer = millis();
}

function mouseMoved() {
  // If mouse is inside canvas coordinates in Julia mode, morph constant c
  if (currentMode === 'julia' && mouseX >= 0 && mouseX <= width && mouseY >= 0 && mouseY <= height) {
    let cr = map(mouseX, 0, width, -1.5, 1.5);
    let ci = map(mouseY, 0, height, -1.5, 1.5);
    crSlider.elt.value = cr;
    ciSlider.elt.value = ci;
    document.getElementById('crVal').textContent = cr.toFixed(2);
    document.getElementById('ciVal').textContent = ci.toFixed(2);
    triggerFastMode();
  }
}

function mouseDragged() {
  mouseMoved();
}

function resetCanvas() {
  background(10);
  if (currentMode === 'tree') {
    windAngle = 0;
  }
}

// ----------------------------------------------------
// 1. Bitwise Landscapes (The Original Project Concept)
// ----------------------------------------------------
function drawBitwise() {
  // Accumulate frames without clearing background to build the scatter pattern
  let nPoints = bitwisePointsSlider ? parseInt(bitwisePointsSlider.value()) : 1000;
  let colorLimit = bitwiseColorSlider ? parseInt(bitwiseColorSlider.value()) : 128;
  let opType = bitwiseOpSelect ? bitwiseOpSelect.value() : 'xor_and';
  
  strokeWeight(1);
  for (let i = 0; i < nPoints; i++) {
    let x = random(0, canvasSize);
    let y = random(0, canvasSize);
    
    // Perform bitwise logic mappings
    let val = 0;
    if (opType === 'xor_and') {
      val = (x ^ y);
      stroke(val % colorLimit, (x & y) % 180, (x | y) % 255, 150);
      point(x | y, x & y);
      point(x & y, x ^ y);
    } else if (opType === 'xor_or') {
      val = (x ^ y);
      stroke((x & y) % 255, val % colorLimit, (x | y) % 180, 150);
      point(x ^ y, x | y);
      point(x & y, x ^ y);
    } else if (opType === 'and_or') {
      val = (x & y);
      stroke(val % colorLimit, (x | y) % colorLimit, (x ^ y) % 255, 150);
      point(x & y, x | y);
    }
  }
}

// ----------------------------------------------------
// 2. Recursive Trees (Organic Swaying Dynamics)
// ----------------------------------------------------
function drawTree() {
  background(10); // Clear screen for animation
  
  let angleVal = treeAngleSlider ? parseFloat(treeAngleSlider.value()) : 30;
  let scaleVal = treeScaleSlider ? parseFloat(treeScaleSlider.value()) : 0.67;
  let depth = treeDepthSlider ? parseInt(treeDepthSlider.value()) : 8;
  let windForce = treeWindSlider ? parseFloat(treeWindSlider.value()) : 4;
  
  let theta = radians(angleVal);
  
  // Calculate dynamic wind offset using Perlin Noise
  let windSpeed = 0.015;
  windAngle += windSpeed;
  let windSway = map(noise(windAngle), 0, 1, -0.05 * windForce, 0.05 * windForce);
  
  // Start the tree base at the bottom-center
  push();
  translate(width / 2, height - 30);
  stroke(212, 165, 116); // primary color trunk
  strokeWeight(depth + 1);
  
  let initialLength = 110;
  line(0, 0, 0, -initialLength);
  
  // Translate to first fork node
  translate(0, -initialLength);
  branch(initialLength * scaleVal, theta, depth - 1, scaleVal, windSway);
  pop();
}

function branch(len, theta, d, scaleVal, windSway) {
  if (d <= 0 || len < 4) return;
  
  // Dynamic stroke weight decreasing with depth
  strokeWeight(d + 0.8);
  
  // Calculate leaves color at tips (d <= 3)
  if (d <= 3) {
    stroke(56, 161, 105, 180); // Organic Leaf Green
  } else {
    stroke(212, 165, 116, 220); // Trunk beige
  }
  
  // --- Right Branch ---
  push();
  rotate(theta + windSway); // Apply angle + wind deflection
  line(0, 0, 0, -len);
  translate(0, -len);
  branch(len * scaleVal, theta, d - 1, scaleVal, windSway);
  pop();
  
  // --- Left Branch ---
  push();
  rotate(-theta + windSway);
  line(0, 0, 0, -len);
  translate(0, -len);
  branch(len * scaleVal, theta, d - 1, scaleVal, windSway);
  pop();
}

// ----------------------------------------------------
// 3. Mandelbrot Set (Complex Math Planes)
// ----------------------------------------------------
function drawMandelbrot() {
  let maxIt = iterationsSlider ? parseInt(iterationsSlider.value()) : 50;
  let zoom = zoomSlider ? parseFloat(zoomSlider.value()) : 1.0;
  let palette = paletteSelect ? paletteSelect.value() : 'hsl';
  
  loadPixels();
  
  // Mandelbrot Center Offset Coordinates
  let cxOffset = -0.5;
  let cyOffset = 0.0;
  
  for (let x = 0; x < width; x += pixelScale) {
    for (let y = 0; y < height; y += pixelScale) {
      
      // Map screen pixel to Complex plane: c = a + bi
      let a = map(x, 0, width, -2.0 / zoom + cxOffset, 1.0 / zoom + cxOffset);
      let b = map(y, 0, height, -1.5 / zoom + cyOffset, 1.5 / zoom + cyOffset);
      
      let ca = a;
      let cb = b;
      
      let zx = 0.0;
      let zy = 0.0;
      
      let n = 0;
      while (n < maxIt) {
        // complex squaring: z_next = z^2 + c ⟹ (zx + zy*i)^2 = zx^2 - zy^2 + 2*zx*zy*i
        let zx2 = zx * zx;
        let zy2 = zy * zy;
        
        if (zx2 + zy2 > 4.0) {
          break; // diverges
        }
        
        let nextZx = zx2 - zy2 + ca;
        let nextZy = 2.0 * zx * zy + cb;
        zx = nextZx;
        zy = nextZy;
        n++;
      }
      
      // Determine pixel color based on iterations and palette
      let col = getPaletteColor(n, maxIt, palette);
      
      // Set pixel values
      for (let px = 0; px < pixelScale; px++) {
        for (let py = 0; py < pixelScale; py++) {
          let screenX = x + px;
          let screenY = y + py;
          if (screenX < width && screenY < height) {
            let pixIndex = 4 * (screenX + screenY * width);
            pixels[pixIndex] = col[0];     // R
            pixels[pixIndex + 1] = col[1]; // G
            pixels[pixIndex + 2] = col[2]; // B
            pixels[pixIndex + 3] = 255;    // A
          }
        }
      }
    }
  }
  updatePixels();
}

// ----------------------------------------------------
// 4. Julia Set (Complex Coordinates Morphing)
// ----------------------------------------------------
function drawJulia() {
  let maxIt = iterationsSlider ? parseInt(iterationsSlider.value()) : 50;
  let zoom = zoomSlider ? parseFloat(zoomSlider.value()) : 1.0;
  let cr = crSlider ? parseFloat(crSlider.value()) : -0.7;
  let ci = ciSlider ? parseFloat(ciSlider.value()) : 0.27;
  let palette = paletteSelect ? paletteSelect.value() : 'hsl';
  
  loadPixels();
  
  for (let x = 0; x < width; x += pixelScale) {
    for (let y = 0; y < height; y += pixelScale) {
      
      // Map screen pixel to Complex plane: z = a + bi
      let a = map(x, 0, width, -1.5 / zoom, 1.5 / zoom);
      let b = map(y, 0, height, -1.5 / zoom, 1.5 / zoom);
      
      let zx = a;
      let zy = b;
      
      let n = 0;
      while (n < maxIt) {
        let zx2 = zx * zx;
        let zy2 = zy * zy;
        
        if (zx2 + zy2 > 4.0) {
          break; // diverges
        }
        
        let nextZx = zx2 - zy2 + cr;
        let nextZy = 2.0 * zx * zy + ci;
        zx = nextZx;
        zy = nextZy;
        n++;
      }
      
      let col = getPaletteColor(n, maxIt, palette);
      
      // Set pixel values
      for (let px = 0; px < pixelScale; px++) {
        for (let py = 0; py < pixelScale; py++) {
          let screenX = x + px;
          let screenY = y + py;
          if (screenX < width && screenY < height) {
            let pixIndex = 4 * (screenX + screenY * width);
            pixels[pixIndex] = col[0];
            pixels[pixIndex + 1] = col[1];
            pixels[pixIndex + 2] = col[2];
            pixels[pixIndex + 3] = 255;
          }
        }
      }
    }
  }
  updatePixels();
}

// ----------------------------------------------------
// Color Palette Generator
// ----------------------------------------------------
function getPaletteColor(n, maxIt, type) {
  if (n === maxIt) {
    return [10, 12, 16]; // Default Dark Slate background
  }
  
  let norm = n / maxIt;
  
  if (type === 'hsl') {
    // Smooth HSL rainbow cycling
    let hueVal = (norm * 360) % 360;
    let rgb = hslToRgb(hueVal, 0.7, 0.5);
    return rgb;
  } else if (type === 'fire') {
    // Solar fire oranges/yellows
    let r = map(pow(norm, 0.5), 0, 1, 30, 255);
    let g = map(pow(norm, 1.5), 0, 1, 0, 200);
    let b = map(pow(norm, 3.0), 0, 1, 0, 50);
    return [r, g, b];
  } else if (type === 'neon') {
    // Cosmic pink and blue neon
    let r = map(sin(norm * PI * 2), -1, 1, 50, 230);
    let g = map(cos(norm * PI), -1, 1, 30, 100);
    let b = map(sin(norm * PI + HALF_PI), -1, 1, 150, 255);
    return [r, g, b];
  } else if (type === 'matrix') {
    // Matrix computer terminal green
    let g = map(pow(norm, 0.6), 0, 1, 30, 230);
    return [15, g, 20];
  }
  
  return [255, 255, 255];
}

// Helper HSL to RGB converter
function hslToRgb(h, s, l) {
  let r, g, b;
  h /= 360;
  
  if (s == 0) {
    r = g = b = l; // achromatic
  } else {
    const hue2rgb = (p, q, t) => {
      if (t < 0) t += 1;
      if (t > 1) t -= 1;
      if (t < 1/6) return p + (q - p) * 6 * t;
      if (t < 1/2) return q;
      if (t < 2/3) return p + (q - p) * (2/3 - t) * 6;
      return p;
    };
    
    const q = l < 0.5 ? l * (1 + s) : l + s - l * s;
    const p = 2 * l - q;
    
    r = hue2rgb(p, q, h + 1/3);
    g = hue2rgb(p, q, h);
    b = hue2rgb(p, q, h - 1/3);
  }
  
  return [Math.round(r * 255), Math.round(g * 255), Math.round(b * 255)];
}

// ----------------------------------------------------
// UI HUD Updates
// ----------------------------------------------------
function updateHUD() {
  const statsSpan = document.getElementById('canvasStats');
  if (statsSpan) {
    let modeText = "";
    if (currentMode === 'bitwise') modeText = "Bitwise Landscape";
    else if (currentMode === 'tree') modeText = "Recursive Tree";
    else if (currentMode === 'mandelbrot') modeText = "Mandelbrot Set";
    else if (currentMode === 'julia') modeText = "Julia Set";
    
    statsSpan.innerHTML = `<i class="fas fa-tachometer-alt"></i> FPS: ${Math.round(frameRate())} | Mode: ${modeText} ${isInteracting ? '(Preview Low-Res)' : ''}`;
  }
}
